### ISSUE TITLE
Tweak search rankings

### ISSUE THREAD

**Issue by bcorrigan** [bcorrigan/shelfcontrol#17]
A lot of searches are quite annoying because of spammy results.

tantivy seems to do some OR search by default with a lot of unwanted results, eg creator:"SOme Author" someterm doesn't give you all the records where creator is some author mentioning someterm, but just gives a superset of both.

I may need to insert ANDs to the search (and omit doing so if it contains AND or OR already).

Also rankings need improved - results where creator matches exactly should come before results where description matches for example.

**Comment by bcorrigan** [comment]
Also surely if a result has words together it should be ranked very highly? But eg if I search for "cassandra complex" then a book containing those words together in title is ranked 10th while books containing them far apart in description are ranked before it - so I'm doing something wrong with tantivy.

**Comment by fulmicoton** [comment]
I am not entirely sure I understood the problem, but if you want to change the default behavior to have combine your terms with a AND instead of OR, you can call `set_conjunction_by_default` on the query parser.

https://docs.rs/tantivy/0.10.1/tantivy/query/struct.QueryParser.html#method.set_conjunction_by_default


> Also surely if a result has words together it should be ranked very highly? But eg if I search for "cassandra complex" then a book containing those words together in title is ranked 10th while books containing them far apart in description are ranked before it - so I'm doing something wrong with tantivy.

As for the second part... tantivy scoring is far from great right now. There is a plan to switch to BM25F instead of BM25.

**Comment by bcorrigan** [comment]
Ah thank you! It sounds like set_conjunction_by_default will certainly solve my problem. Tbh this issue is just a reminder to myself to RTFM and work out how I can make better use of tantivy - I am sure probably all of my problems can be addressed with a bit of effort by me.

Thanks a lot for tantivy, it really does perform amazingly well.

**Comment by bcorrigan** [comment]
FIxed
